name: Add to Exchange and Deploy to Sandbox

on:
  push:
    branches:
      - releases/**
      - dev

env:
  USERNAME: ${{ secrets.anypoint_platform_username }}
  PASSWORD: ${{ secrets.anypoint_platform_password }}
  ENVID: ${{ secrets.sandbox_env_client_id }}
  ENVSECRET: ${{ secrets.sandbox_env_client_secret }}

jobs:
  exchangedep:
    runs-on: ubuntu-latest
    env:
      working-directory: ./cicd-demo-wt-githubactions
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "anypoint-exchange-v3", "url": "https://maven.anypoint.mulesoft.com/api/v3/maven" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "${env.USERNAME}", "password": "${env.PASSWORD}" }]'
    - name: Deploy to Exchange
      working-directory: ./cicd-demo-wt-githubactions
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn -e -X clean deploy \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD"

  deploy:
    needs: exchangedep
    runs-on: ubuntu-latest
    env:
      working-directory: ./cicd-demo-wt-githubactions
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Deploy to Sandbox
      working-directory: ./cicd-demo-wt-githubactions
      run: |
        mvn -e -X clean deploy -DmuleDeploy \
         -Denvironment="Sandbox" \
         -Pdev \
         -Danypoint.psname="ps-ym-demo01" \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD" \
         -Danypoint.env.id="$ENVID" \
         -Danypoint.env.secret="$ENVSECRET"
