name: Build and Deploy to Sandbox

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
jobs:  
  exchangedep:
    runs-on: ubuntu-latest
    env:
      working-directory: ./cicd-demo-wt-githubactions
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: maven-settings-xml-action
      env:
        USERNAME: ${{ secrets.anypoint_platform_username }}
        PASSWORD: ${{ secrets.anypoint_platform_password }}
      uses: whelk-io/maven-settings-xml-action@v20
      with:
        repositories: '[{ "id": "anypoint-exchange-v3", "url": "https://maven.anypoint.mulesoft.com/api/v3/maven" }]'
        servers: '[{ "id": "anypoint-exchange-v3", "username": "${env.$USERNAME}", "password": "${env.PASSWORD}" }]'
    - name: Deploy to Exchange
      env:
        USERNAME: ${{ secrets.anypoint_platform_username }}
        PASSWORD: ${{ secrets.anypoint_platform_password }}
      working-directory: ./cicd-demo-wt-githubactions
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn -e -X clean deploy \
         -Denvironment="Sandbox" \
         -Danypoint.psname="ps-ym-demo01" \
         -Danypoint.username="$USERNAME" \
         -Danypoint.password="$PASSWORD" 
  
  deploy:
    needs: exchangedep
    runs-on: ubuntu-latest
    env:
      working-directory: ./cicd-demo-wt-githubactions
    steps:    
    - name: Checkout this repo
      uses: actions/checkout@v3
    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Deploy to Sandbox
      env:
        USERNAME: ${{ secrets.anypoint_platform_username }}
        PASSWORD: ${{ secrets.anypoint_platform_password }}
        ENVID: ${{ secrets.env_client_id }}
        ENVSECRET: ${{ secrets.env_client_secret }}
      working-directory: ./cicd-demo-wt-githubactions
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn -e -X clean deploy -DmuleDeploy \
         -Denvironment="Sandbox" \
         -Danypoint.psname="ps-ym-demo01" \
         -Danypoint.username="$USERNAME" \
         -Danypoint.username="$USERNAME" \
         -Danypoint.username="$ENVID" \
         -Danypoint.password="$ENVSECRET" 
